### ISSUE TITLE
Wrong variable in Detail.html

### ISSUE THREAD

**Issue by gmt-it** [derhansen/plain_faq#86]
Hello.

in \plain_faq-main\Resources\Private\Templates\Faq\Detail.html the wrong variable is used for the back link:

  <f:if condition="**{settings.listPid**}">
    <f:link.page pageUid="**{settings.listPid}**"><f:translate key="labels.backToList" /></f:link.page>
  </f:if>

I think settings.detailPid should be used there.

Is there already an adjustment for Typo3 13?

Best regards

Guido

**Comment by derhansen** [comment]
Why do you think this should be `{settings.detailPid}`. The link should go back to the list view, which is defined in `{settings.listPid}`. So from my point of view, this is correct.

A TYPO3 v13 compatible version of the extension will be released this year, but most likely after the v13.4 core release in october, since I do not have time currently to work on this extension.

**Comment by gmt-it** [comment]
Hi. You are right. 
I use plainfaq_pilistdetail. The detail view is displayed but the backlink always points to the folder that contains the faq records. 

I'm trying to get it to work under Typo3 13.2.1.
